language: go

go:
  - "1.16"

os:
  - linux

git:
  depth: 1
  quiet: true
  submodules: false

notifications:
  email: false

script:
  ./test.sh

after_success:
  bash <(curl -s https://codecov.io/bash)
