version: "3"

networks:
  db:
    driver: bridge

services:
  http:
    build: 
      dockerfile: cmd/http_server/Dockerfile
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      DB_DSN: "postgres://user:password@postgres:5432/postgres?sslmode=disable"
      HTTP_SERVER_ADDR: ":8080"
    networks:
      - db
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 5s
      retries: 10
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - db
